apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
stringData:
  mongodb-root-username: root
  mongodb-root-password: password
  mongodb-username: todo-user
  mongodb-password: todo-pass
