apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
type: Opaque
stringData:
  mongodb-username: todo-user
  mongodb-password: todo-pass
  mongodb-database: todo
  mongodb-authentication-database: todo
